### ISSUE TITLE
KINDLY_STYLE_GUIDE.md

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/kindly#108]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
<hr>

# Expected Behaviour

Should guide contributors on how to adhere to the kindly image guide in their styling of the page.

# Current Behaviour

Things are a bit topsy turvy 😵‍💫 

- Combine style guide and best practice until one cohesive document

**Comment by camelPhonso** [comment]
@nichgalzin you were quite keen on a style guide existing but also loathe to create documentation so you might be into this suggestion - let's use [Storybook](https://storybook.js.org/tutorials/intro-to-storybook/react/en/get-started/) instead!

We can:
- document all our components **by writing code**
- provide everyone with a clear library of existing components and their different states
- test different component interactions with UI displayed in the storybook console
- automate those tests in our CI pipeline with GitHub actions ✨ 

[This video](https://youtu.be/Lg-hT0O2F7E?feature=shared) shows a nice example of testing a form component 📺 

Don't think it's a priority at this moment but maybe a good one to team up on?

**Comment by eliazzo** [comment]
Closing and replacing with #221
