### ISSUE TITLE
MessageForm.tsx - Stop users from sending empty messages

### ISSUE THREAD

**Issue by eliazzo** [enBloc-org/kindly#120]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
<hr>

# Expected Behaviour
- users should not be able to send empty messages
- Implement message send on key ```enter```
- ```shift enter``` to add a new line

# Current Behaviour

Currently users can submit new messages  in `MessageForm.tsx` without any content

<hr/>
# Steps to recreate the issue

 1. Navigate to `/conversations`
 2. Click "send message" button without adding any text to the form
 3. A new empty message has been created

**Comment by PAZHames** [comment]
Please could I be assigned to this issue along with Lucy?

**Comment by JasonWarrenUK** [comment]
🤌🏼
