### ISSUE TITLE
Accessibility testing - messaging

### ISSUE THREAD

**Issue by eliazzo** [enBloc-org/kindly#121]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
<hr>

# Expected Behaviour

Can be used with screen reader and on multiple devices

# Current Behaviour

No accessibility tests in place

# Additional notes
- Playwright have an accessibility API that can be used to inspect the accessibility tree and ensure compliance with standards like WCAG

- Depending on how easy this is to use we can use other accessibility tools e.g. lighthouse

**Comment by eliazzo** [comment]
Look into cypress accessibility testing options once migration is complete

**Comment by camelPhonso** [comment]
Now dependent on #163

**Comment by ShaughnAnderson94** [comment]
plan to check if any qas experienced with this
