### ISSUE TITLE
Auto Conversation restart.

### ISSUE THREAD

**Issue by ShaughnAnderson94** [enBloc-org/kindly#124]
Latest update as of Fri 12 Jul 24

**⚠️ This issue is currently in progress and can be found on branch #124/auto-conversation-restart. The restart functionality is working, but not consistently. If anyone is available to take a look into this help would be greatly appreciated! ⚠️**

# Expected Behaviour
If user 1 deletes a conversation and their partner (user 2) continues to send messages, the conversation should be restarted for user 1 and the message history should be displayed

# Current Behaviour

If user 1 deletes conversation and their partner (user 2) continues to send messages, only the user 2 can see the message history

# Files changed

**markConversationAsDeleted.ts***
- updates the member_has_deleted bool in the conversations table

**deleteConversation.ts**
- calls markConversationAsDeleted to update the member_has_deleted bool 

**restartConversation.ts**
- reinserts the deleted row into user_conversations with the conversation data
- calls markConversationAsDeleted to update the member_has_deleted bool 

**components/messaging/ConversationsList.tsx**
- a supabase watcher looks for updates to the conversations table (member_has_deleted)
- if there is a change, the payload is modified to mark member_has_deleted as true within the conversations object of the payload
- a handler checks if the updated conversation is part of allConversations. If found, and if member_has_deleted is marked as true in the updated payload, it updates this value in the corresponding conversation in the state

**components/messaging/CurrentConversation.tsx**
- updated MessageForm component props

**components/messaging/MessageForm.tsx**
- check if member_has_deleted is true, which means a conversation member had previously marked the conversation as deleted
- if the conversation has been marked as deleted, the restartConversation function is called
- After restarting the conversation, the state update for the currentConversation is performed to reset the member_has_deleted flag to false

**Comment by ShaughnAnderson94** [comment]
Idea for implementing this. It would be in the current conversation component you have the conversation ID there so you can make a call to userconversations when a message is sent that checks if there are one or two rows in the table with that conversation id and if one does the restart

**Comment by nichgalzin** [comment]
Do we want this to incorporate the new ideas we have about deleting a conversation and related behaviours, and for clarification what is that?
 - Deleting a conversations removes it from database, but just for you.
 - When a user types in a conversation that's been deleted by the other user, the conversation restarted for that user. 

Is this right?

**Comment by ShaughnAnderson94** [comment]
> Do we want this to incorporate the new ideas we have about deleting a conversation and related behaviours, and for clarification what is that?
> 
> * Deleting a conversations removes it from database, but just for you.
> * When a user types in a conversation that's been deleted by the other user, the conversation restarted for that user.
> 
> Is this right?

I have been thinking about this and am not sure about the 2nd part since it would be easy and useful to provide the user who deleted the conversation with the old messages in fact it would make things a lot easier if we do since we can go back to showing both users the same conversation rather than each of them looking at different sets of messages from either different tables or different starting points in the same table. I will add a draft of how I am thinking to approach this by end of today and will wait to start till we have clarity on this

**Comment by ShaughnAnderson94** [comment]
Just off the top of my head could be other approaches
possible draft structures @nichgalzin @camelPhonso 

**No database change keeping conversations the same:**

Every time someone sends a message we check if there is an entry in user_conversations that has this conversations id and the conversation partners id if yes we run the usual call adding the message if no we recreate the entry in the user_conversations table using the same logic we initially created it with. When only one person deletes a conversation table the only change is that their version is removed from the user_conversations table so this will restore the conversation to exactly what it was before
pros: No database changes
Cons: doubles the number of supabase calls each time message button is clicked may hurt responsiveness

**Database change keeping the conversations the same:** 

we add a deleted_by_a_member column to the conversations table(which is no ticked to true as part of the delete conversation function) and make that part of what we get whenever we call the database for information to display a conversation. When send message is clicked we can check this and then decide if we just need to send messages or need to both restore the user_conversations and send a message.
pros: we add small complexity the database deletion call and the call to get information for the conversation but we need no additional calls to the database and still make just one whenever the message button is clicked
Cons: none besides having to update the database really

**No database change only person who did not delete has old messages:** 

This could work if we add additional logic to the database call we make when we send a message instead of just pushing that message to the conversation whose id you are currently in you also push that message to any conversation with the same item _id and conversation partner_id this mean both the original conversation and new conversation get updated. Both members will see just one conversation and only one of them will have the original conversation
Pros: Honestly not that much until someone comes up with a smoother way of doing it I am against it
Cons: A lot of work for very little see above


**Database change only person who did not delete has old messages:**

Instead of a boolean added to the conversations table the deleted by a user now contains an object with the person who deleted it and the length when it was deleted (this can be an array of objects if we want to handle the conversation being deleted multiple times by different people but not at the same time) if there is nothing in this column conversations behave normally. If there is then users whose id match the object are shown the conversation starting from the length at time of deletion +1. (or if using the array bit then both users are shown from the point dictated by the object with their id farthest along in the array)
Pros: less work then doing this without the database
Cons: Still more work than restoring old message via either method

**Comment by camelPhonso** [comment]
Thanks @ShaughnAnderson94 - The second option seems the best so I'd be pretty happy with us following that route 👍

**Comment by nichgalzin** [comment]
First: I think it's really cool and good to have a chat about implementation of ideas in this way. We should do this more!
  And also, I think the second method it also a straight forward and possibly sound solution for this. Only thing I would add is that we may need to review some of the triggers I have set up on Supabase that get set off when people delete conversations. I don't think that they will cause any issue and I think that they should still work as intended - that behaviour being that when both people delete a conversation it removes it from the conversatio table and cleans up all the messages from the conversation table as well. But we should double check. 

This might be a way of implementing idea two:

## Soft Deletion with a Visibility Toggle

Implement a "soft delete" mechanism where, instead of actually removing conversations from the user_conversations table, you add a visibility flag (e.g., is_visible boolean column) for each user involved in a conversation. When a user elects to delete a conversation, this flag is set to false for them, effectively hiding the conversation from their view without affecting the other participant(s).
