### ISSUE TITLE
Automatically set new conversation as currentConversation

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/kindly#133]
# Expected Behaviour

When the user is re-directed to the `/conversations` page after opening a new conversation that should be the conversation displayed on the page as `currentConversation`

# Current Behaviour

When a new conversation is started from within an `/item[id]` page the user is redirected to `/conversations` but the newly created conversation is displayed in a `ConversationCard` at the bottom of `ConversationsList` and a different conversation is set as `currentConversation`

<hr>

# Failure Information

This issue does not break the app -  the user can keep navigating. It's simply a bug in the expected behaviour of the app.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Navigate to the item page of any item that you have not submitted yourself
2. Click the `Message` button
3. You will be redirected to the `/conversations` page but a different conversation will be currently open

## Failure Logs

This behaviour does not produce any failure logs - the code continues running without failure.

**Comment by oskarprzybylski23** [comment]
@camelPhonso Could you assign this issue to me please?

**Comment by eliazzo** [comment]
Hi @oskarprzybylski23, are you still working on this issue or should we reassign it as we know you must be busy 🌞

**Comment by oskarprzybylski23** [comment]
Hi @eliazzo. Feel free to reassign, I am not currently working on this.

**Comment by fintonius** [comment]
Hi @eliazzo can I be assigned this issue?

**Comment by camelPhonso** [comment]
@fintonius Looking at the current code in `dev` it looks like recent merges have combined to enforce the behaviour we expected. 

This issue is currently solved so we will close it as resolved. Thanks for offering to take it anyhow.
