### ISSUE TITLE
🐞 ConversationsList overflow 🐛 

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/kindly#140]
# Expected Behaviour

When a user has a long list of conversations active the `ConversationCard`s should scroll on `ConversationsList`

# Current Behaviour

`ConversationsList` is static and forces the page to expand
![Screenshot 2024-03-26 at 16 11 35](https://github.com/enBloc-org/kindly/assets/114600712/c89e30be-f763-4e83-9e36-359842d0b148)

<hr>

# Failure Information

The code does not fail 💡 it creates the behaviour demonstrated above

## Steps to Reproduce

1. Log in
2. Find an item
3. Create a new conversation by clicking the "Message" button
4. Repeat this until your `/conversations` page displays enough `ConversationCard`s to overflow the page

## Failure Logs

No failure :)

**Comment by fintonius** [comment]
here I am!

**Comment by khanSoliheen** [comment]
@Edga380 , could you please lemme know how did you sign up. I am getting an error while signing up.  ⨯ Error: Your project's URL and Key are required to create a Supabase client!

Check your Supabase project's API settings to find these values

https://supabase.com/dashboard/project/_/settings/api
    at createClient (./utils/supabase/server.ts:8:77)
    at $$ACTION_0 (signup/page.tsx:56:90)
I went to this url I can see I am able to get NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_ANON_KEY. But, what about others?

NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
GMAIL_APP_USERNAME=
GMAIL_APP_PASSWORD=
AWS_AMPLIFY=
TEST_USER_EMAIL=
TEST_USER_PASSWORD=

**Comment by camelPhonso** [comment]
> ... could you please lemme know how did you sign up. I am getting an error while signing up. ⨯ Error: Your project's URL and Key are required to create a Supabase client!
> 
> Check your Supabase project's API settings to find these values
> 
> https://supabase.com/dashboard/project/_/settings/api at createClient (./utils/supabase/server.ts:8:77) at $$ACTION_0 (signup/page.tsx:56:90) I went to this url I can see I am able to get NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_ANON_KEY. But, what about others? Thanks for the help mate.
> 
> NEXT_PUBLIC_SUPABASE_URL= NEXT_PUBLIC_SUPABASE_ANON_KEY= GMAIL_APP_USERNAME= GMAIL_APP_PASSWORD= AWS_AMPLIFY= TEST_USER_EMAIL= TEST_USER_PASSWORD=

@khanSoliheen reach out to us on discord via the invite link in the documentation and we can help you out :)
