### ISSUE TITLE
🐜 Limit conversations to 1 per item/user pair

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/kindly#141]
# Expected Behaviour

If you already have an active conversation with a particular user about an item it should be impossible to start a second conversation with the same user about the same item

# Current Behaviour

If a user with the 'refugee' type starts a conversation with a 'donor' they can navigate back to the same item page and start a second conversation with that 'donor' about the same item.

You can end up with this:
![Screenshot 2024-03-26 at 16 23 03](https://github.com/enBloc-org/kindly/assets/114600712/9e2d3485-38f0-4372-8318-3e4149138802)

<hr>

# Failure Information

No failure - this bug does not break the code but it creates unwanted behaviour

## Steps to Reproduce

1.Log in as a refugee
2. Find an item
3. Start a conversation by clicking the "Message" button
4. Navigate back to the same item
5. Repeat steps '3' and '4' as many times as you want...

## Failure Logs

No failures 🪲

**Comment by Luciensday** [comment]
can I be assigned to this issue please :0

**Comment by camelPhonso** [comment]
The associated PR (#197) has been merged. Closing this issue as completed
