### ISSUE TITLE
🪲Unable to register as new user #bug

### ISSUE THREAD

**Issue by Luciensday** [enBloc-org/kindly#145]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
<hr>

<hr>
(only complete the following if reporting a bug 🪲 - delete otherwise)

# Failure Information

As new user - I am unable to sign up after filled out the information 

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. I attempted to sign up via  https://kindly-v2zt.vercel.app/signup
2. After filled up to form and submit 
3. The route being re-direct, however the reason of "could not authenticate user" is not clear. The route being re-direct is   https://kindly-v2zt.vercel.app/signup?message=Could%20not%20authenticate%20user

## Failure Logs

After my attempt to sign up as user

<img width="538" alt="Screenshot 2024-03-28 at 09 45 21" src="https://github.com/enBloc-org/kindly/assets/128807685/29bb76aa-2dbd-4aff-8183-4666cc4ee057">

**Comment by camelPhonso** [comment]
@Luciensday thanks for submitting this - it's highlighted that we're showing people the deployed site from the original build, which does not match the forked development environment in this repo.

Please follow the guidance in our [before your first issue](https://github.com/enBloc-org/kindly/blob/dev/.github/BEFORE_YOUR_FIRST_ISSUE.md) to clone the repo and try to sign up from the dev branch once that is up and running.

I'm closing this issue with the caveat that the team is removing the link to the old deployed version from our repo.
