### ISSUE TITLE
Missing links from CONTRIBUTING.md

### ISSUE THREAD

**Issue by PAZHames** [enBloc-org/kindly#156]
# Expected Behaviour

Under contributing, documentation should contain links to 'Best Practices' and 'Installation Guide'

# Current Behaviour

Names of documents are included, but links are not attached

<img width="1100" alt="Screenshot 2024-04-09 at 11 04 06" src="https://github.com/enBloc-org/kindly/assets/77605055/1c71a836-191a-42d4-ab0a-23f86f133e16">

## Steps to Reproduce
1. Open documentation at https://github.com/enBloc-org/kindly/blob/dev/.github/CONTRIBUTING.md
2. Scroll to 'Contributing Code'

**Comment by camelPhonso** [comment]
Picking this one up as I have spotted the need to also adjust some of the guidance we give:

* Directions on creating a new branch need to be adjusted to guide people through forking the repo first (you were onto something @PAZHames )
* There are some references to the old `ISSUE_TEMPLATE.md` file that are no longer relevant and make little sense in the current context.
