### ISSUE TITLE
Update conversation when item is no longer available

### ISSUE THREAD

**Issue by eliazzo** [enBloc-org/kindly#169]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
<hr>

# Expected Behaviour

All conversations should see a message saying the item is unavailable eg
![item unavailable](https://github.com/enBloc-org/kindly/assets/114364165/6698cf96-f21f-4c36-a162-beb2c850e97a)

# Current Behaviour

Conversation can continue (no change to conversation) when item is removed

**Comment by camelPhonso** [comment]
Moved to `blocked` as it will need to wait on issue #183
