### ISSUE TITLE
Update documentation with Discord server

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/kindly#174]
# Expected Behaviour

Documentation should guide new contributors towards reaching the core team on discord and getting access to .env variables needed for their setup.

# Current Behaviour

Reference to the discord server is missing from the current version of our documentation.

**Comment by Duncankatia** [comment]
It looks like discord link here does not point to #starthere Chanel ![image](https://github.com/enBloc-org/kindly/assets/156337997/bfe646d6-4bad-4c04-8841-64e972b4a119)
