### ISSUE TITLE
Only allow users to have one profile picture stored in bucket.

### ISSUE THREAD

**Issue by ShaughnAnderson94** [enBloc-org/kindly#200]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
<hr>

# Expected Behaviour

```
when a profile gets deleted the associated image with it should be removed from supabase storage
```

# Current Behaviour
I checked deleting a profile and it did not delete it. We should look into what happens when you change profile images and when you delete items to see how wide spread this is
```


## Steps to Reproduce
```

1.Create profile and upload profile image
2. go to supabase and get the image reference save it somewhere
3. delete profile
4. Search in the list of photos stored on super base and confirm it is still there
```

**Comment by nichgalzin** [comment]
This functionality will like need to be used in issue #193 as well
