### ISSUE TITLE
Update UI 'message' button when conversation has already been started

### ISSUE THREAD

**Issue by eliazzo** [enBloc-org/kindly#201]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
<hr>

# Expected Behaviour
If a conversation has already been started the 'message' button should appear differently e.g., 'go to conversation'

When button is clicked user should be taken to the conversation that relates to the item (and not the most recent conversation)

# Current Behaviour
<img width="814" alt="Screenshot 2024-05-10 at 11 40 56" src="https://github.com/enBloc-org/kindly/assets/114364165/3aa88faa-88e6-4c15-a114-e7b26af747fa">

**Comment by camelPhonso** [comment]
Closing this issue following a change in strategy now being implemented via PR #197
