### ISSUE TITLE
MESSAGING - no messages if you did not click on the checkbox when registering

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/kindly#219]
_Steps to recreate:_

I've signed up for KINDLY but forgot to click on the next checkbox.

> ![Image](https://github.com/enBloc-org/kindly/assets/113237479/0da5bfd6-da4d-4740-b2e5-ab4deab0e749)

As a result, I don't have access to the messaging feature. 

> 1. When I go to items, I don't see the enquiry button.
> ![Image](https://github.com/enBloc-org/kindly/assets/113237479/e5a740fd-daca-4f21-b6d7-f814813703f3)

However, I can add items for donations and I did post this one - https://cool-creponne-3e1272.netlify.app/item/191

_The issue I've got:_ I've received a message regarding my item, but because I did not click on the check box when registering, I cannot view it. I know that I've got a message because I received the following email:

> ![Image](https://github.com/orgs/enBloc-org/projects/4/assets/113237479/c285420d-1e07-46c9-90b0-e6f2d664ea55). 

 Currently, there is no way for me to change the settings and view the message. 

_Suggested solution_: I think many potential users of our website may not self-identify as refugees, but they may still want to donate items. We can make the messaging feature accessible to all users and possibly delete the checkbox when registering 
![Image](https://github.com/enBloc-org/kindly/assets/113237479/7464d937-dd2c-4759-b86a-e4e49452e9c1)

**Comment by camelPhonso** [comment]
Hi @nataliiazab - Thanks for adding this issue

Not having a message button is an intended feature as only refugees should be able to receive donations. However, if a refugee has started a conversation with you and sent a message you should be able to see it in your `/conversations` route, so if that's not happening we will need to triage that potential bug 🤔 

I'll try to test this out soon and update here 👍

**Comment by camelPhonso** [comment]
Hi @nataliiazab I've tested this on my local environment (from the dev branch) and it seems to be working normally. With a refugee user I message my donor account and receive the messages normally.

The one thing we still don't have is a notification showing in the main page that there are new messages (which is planned for the future), but other than that the feature is working as expected. 

You mentioned before that you tested this with another contributor, can I just confirm if you were both accessing the same containerised copy of the database when you tested? Since our development environment accesses a local copy of the database you would need to share the same `api url` in order to interact with the same set of data, or test this with two users logged from the same server. In my case, I logged with one user on my arc browser and another user in my chrome browser

**Comment by nataliiazab** [comment]
Hi @camelPhonso Sorry that was my fault! I was testing in the deployed environment ([link](https://cool-creponne-3e1272.netlify.app/)) and in my local one (with the main db) but I did not synch my fork :woozy_face: After synchronising it, I tested again and I can see the messages locally. 

> ![Image](https://github.com/enBloc-org/kindly/assets/113237479/9e0a6046-a0bd-4f56-867c-5a1d1e092846)

Thank you very much for taking the time to test and explain the logic! :bow:

**Comment by camelPhonso** [comment]
> Hi [@camelPhonso](https://github.com/camelPhonso) Sorry that was my fault! I was testing in the deployed environment ([link](https://cool-creponne-3e1272.netlify.app/)) and in my local one (with the main db) but I did not synch my fork 🥴 After synchronising it, I tested again and I can see the messages locally.
> 
> > ![Image](https://private-user-images.githubusercontent.com/113237479/333293780-9e0a6046-a0bd-4f56-867c-5a1d1e092846.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MzU4NjgsIm5iZiI6MTcxNjUzNTU2OCwicGF0aCI6Ii8xMTMyMzc0NzkvMzMzMjkzNzgwLTllMGE2MDQ2LWEwYmQtNGY1Ni04NjdjLTVhMWQxZTA5Mjg0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwNzI2MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWZlMzQxYTY4ZmMyMDU1MzdkMTYxYjhkMWEyMzVjYTcxMjAwNGRmMmU5ZDQyMDNmYTFiMTgyOWIyNDM5Yjk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mdPpLYcTV6ISDpFQAFCMtnHvN8wnPIx8qn4Sd9Qp1Xg)
> 
> Thank you very much for taking the time to test and explain the logic! 🙇

Ah no worries! I'm glad everything's working as intended 😅

I'm closing this issue now but maybe if you think the documentation for set up needs any additions to avoid a similar mistake in future feel free to make a new issue suggestion for it :)
