### ISSUE TITLE
Missing NodeJS version requirement

### ISSUE THREAD

**Issue by mnixo** [enBloc-org/kindly#243]
## Expected Behaviour

As a contributor, after I clone the repository I'm able to confirm that I'm running the correct version of Node.js before I run `npm install`.

## Current Behaviour

No NodeJS version is specified in documentation or enforced through tooling.

## Steps to Reproduce

Follow [the installation instructions](https://github.com/enBloc-org/kindly/blob/a5e1b953ccc9c0cf5afac08e0b0a9285b0cae42b/.github/BEFORE_YOUR_FIRST_ISSUE.md#installation). There is no reference to the Node.js version that should be used.

## Considerations

- Specifying the Node.js version provides a direct guideline to help contributors be sure that they have their working environment properly set up.
- By specifying the Node.js version, the NPM version is directly implied.
- This version can also be enforced with tooling, although having it simply mentioned in the documentation would be good enough.
- Different versions of Node.js (and NPM) can produce different results when `npm install`ing and generating the `package-lock.json` file.
- Specifying the major version is usually enough.

Please let me know if I should open a PR for this.

**Comment by camelPhonso** [comment]
Thanks @mnixo - happy to assign this one to you 👍

**Comment by mnixo** [comment]
Thanks @camelPhonso! Please just let me know what version the team is actually using. v20?

**Comment by camelPhonso** [comment]
> Thanks @camelPhonso! Please just let me know what version the team is actually using. v20?

I honestly think there are discrepancies within the core team but v20 seems a good call - we're happy to take your input on this too as you work on the issue 👍
