### ISSUE TITLE
Allow Donors to control the 'Reserved' Status of Items they have uploaded ⏸️ 

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/kindly#254]
# Expected Behaviour

- [ ] Donors should be able to mark their items as 'Reserved' for a specific user
- [ ] Donors should be able to remove the 'Reserved' status from any item they have donated
- [ ] When an Item is reserved, all relevant conversations should receive an update confirming this

# Current Behaviour

Currently the database schema allows for this functionality because it includes in the `items` table the following values:
- `reserved` (this name should be changed to `is_reserved`)
- `reserved_by`

However, these values are not connected to any feature in our codebase at the moment.

## Steps to Reproduce
1. Log into Kindly
2. Visit your profile page (make sure you have uploaded at least one item for donation)
3. There is no option to mark your items as reserved

**Comment by sulphite** [comment]
After discussion the new plan is as follows:
- a user can "request to reserve" through a button on each item page
- this adds their userid to the requestedToReserve column
- (the owner of the item gets a system message about this; this could be a separate issue)
- in a user's donated items list, if anyone has requested to reserve an item there will be a button to control who it is reserved for
- the button opens a modal which displays all the reserve requests with individual accept/deny buttons
- accepting a reserve request updates the status of reserved and reserved_by in the database

**Comment by camelPhonso** [comment]
> After discussion the new plan is as follows:
> 
> * a user can "request to reserve" through a button on each item page
> * this adds their userid to the `requestedToReserve` column
> * (the owner of the item gets a system message about this; this could be a separate issue)
> * in a user's donated items list, if anyone has requested to reserve an item there will be a button to control who it is reserved for
> * the button opens a modal which displays all the reserve requests with individual accept/deny buttons
> * accepting a reserve request updates the status of `reserved` and `reserved_by` in the database

Hey @sulphite !

Thanks for posting this outline, the plan looks great. I know you discussed this for a bit with Nich and your plan is pretty sound but I also want to highlight another route you can choose to take, depending on how the issue progresses:

We can start by letting the donor of an item mark it as reserved for any user that has a conversation with them related to that item. We already have all the utils that handle finding conversations related to an issue and recovering the id of the partner in that conversation. 

Once that feature exists we can then create a new issue to allow refugees to request for this item to be reserved. That request would trigger a system message to be sent to the donor in a conversation between them and the user who request the item.

That brings the issue down to:
- create a button to be displayed in the `itemCard.tsx` of each item in the `donatedItemsList.tsx` that allows the donor to reserve the item
- that button will let the donor select any user who has an active conversation with them about the item
- once a user is selected out of that list the item is marked as reserved and no longer available for inquiries

**Comment by sulphite** [comment]
Hey @camelPhonso thanks for the input! I think splitting it into 2 issues makes the most sense, so I'll get to work on what you suggested
