### ISSUE TITLE
Allow Users to mark their Items as 'Given Away'

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/kindly#260]
# Expected Behaviour

- [ ] Donors should be able to edit the status of their uploaded Items to mark them as "Given Away" at any point
- [ ] Items that have been marked as "Given Away" should no longer be visible in the `/search` page but remain in the database
  - Any existing conversations relating to those Items should be updated with a notification

# spike
Do we want to create a new table to store the reserved items in for data tracking?

# Current Behaviour

There is no option for donors to manage the status of their items at the moment.

This issue relates closely to #254 and should treat it as a dependency

## Steps to Reproduce
1. Log into Kindly
2. Visit your profile page (make sure you have uploaded at least one Item for donation)
3. There is no option to mark your Items as 'Given Away'

**Comment by camelPhonso** [comment]
### answering the spike question in this issue

We do want to track who an item has been reserved for in our database. A planned feature for later in the roadmap is to limit the number of donations the same person can receive within a specific period of time, this will be unlocked by us keeping track of how many items have their `user_id` in their `given_away_to` column

**Comment by ShaughnAnderson94** [comment]
> ### answering the spike question in this issue
> We do want to track who an item has been reserved for in our database. A planned feature for later in the roadmap is to limit the number of donations the same person can receive within a specific period of time, this will be unlocked by us keeping track of how many items have their `user_id` in their `given_away_to` column

It might be easier to control how many items a user takes by having it so a user has a items_requested column (which can be set to reset every so often)

**Comment by YuraPetrovskyi** [comment]
Hello. Is it possible to assign myself for this task, I would be interested in working on it?

**Comment by camelPhonso** [comment]
> Hello. Is it possible to assign myself for this task, I would be interested in working on it?

All yours @YuraPetrovskyi !!

This one will involve some restructuring of the database as you've seen in the comments. I think the rough plans mentioned above should work perfectly well but reach out to the rest of the team if anything odd comes up :)

**Comment by YuraPetrovskyi** [comment]
Hello @all friends, there is something that needs to be discussed. I have managed to implement the following logic:

1. A new column given_away_to has been added to the "Items" table.
2. When a user reserves an item for someone, an additional "Give away" button appears. What this implementation does is that the item can only be given to the person for whom it was reserved.
3. When the user gives away the item, all participants in the conversation related to that item receive a notification: 'This item has been marked as Given Away and is no longer available.', as well as an additional message for the person who received the item: 'Congratulations! The item has been given to you.'
4. The user ID of the person to whom the item was given is copied into the "given_away_to" column.
5. The item that has been given away will not appear on the "/search" page.

There are a few things we need to clarify:

- After the item is given away, what should be done with it? (Should it be deleted, moved somewhere else, etc.?)
- Should the owner of the item still be able to see it on their "/profile" page? 
- Are additional labels needed for the item? (For example, similar to the "RESERVED" label already implemented in the project)
- Is there anything else that I might have overlooked and need to add?

![Image](https://github.com/user-attachments/assets/eb0af8f7-9fd3-4029-8adc-30d6345a5c4c)

**Comment by camelPhonso** [comment]
Hey Yurii, this sounds great! Can't wait to see it in action 😃 

> There are a few things we need to clarify:
> 
> * After the item is given away, what should be done with it? (Should it be deleted, moved somewhere else, etc.?)

We definitely don't want to delete them for now. There is another feature planned for down the road where we will use this to control the number of donations to the same person in a week. For now let's just keep them in the database as is.

> * Should the owner of the item still be able to see it on their "/profile" page?

This is an interesting one. I think we could keep them on the `/profile` page for now and as we work on re-designs then we might decide how to separate these (maybe we'll add a new section or just allow the user to filter them out)

> * Are additional labels needed for the item? (For example, similar to the "RESERVED" label already implemented in the project)

Definitely. I would use the exact same styling as the `reserve` label but saying `given away`

> * Is there anything else that I might have overlooked and need to add?

Nothing I can think of right now :)
