### ISSUE TITLE
Add Password validation

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/kindly#261]
# Expected Behaviour

When creating a new account users should receive feedback to guarantee they set up a valid password.

Acceptable input should include at least:
- 1 number
- 1 special character

# Current Behaviour

Users can set up any password of their choosing without any restrictions from the app.

## Steps to Reproduce
1. Run your local environment
2. Select 'Sign up' at the home screen
3. Enter a password that does not meet the requirements described in this issue
4. You're in 🙃

**Comment by RGHANILOO** [comment]
!request

**Comment by RGHANILOO** [comment]
i am still working on this issue if i can't make any progress with it i will update.

**Comment by camelPhonso** [comment]
@RGHANILOO before you get too bogged down on validating old-school (which I think you were already) look at [this documentation](https://supabase.com/docs/guides/auth/password-security).

Check out how this can be set in your containerised `Studio URL` link and then add a migration - some features are not available through the `Studio URL` but can be edited through the `config.toml` file in our `supabase` directory.

We also have a [prepared script to create a migration file](https://github.com/enBloc-org/kindly/blob/dev/.github/BEFORE_YOUR_FIRST_ISSUE.md#managing-database-migrations) in the end
