### ISSUE TITLE
Upstream image response failed

### ISSUE THREAD

**Issue by YuraPetrovskyi** [enBloc-org/kindly#267]
# Expected Behaviour

After adding a new item, the image uploaded by us is expected to be displayed, and a correct link will be created in the database.

# Current Behaviour
After creating an item, the image is not displayed:
![error 400](https://github.com/enBloc-org/kindly/assets/88290201/7041b72e-7ee6-40e5-a095-4d84dcf8cd19)

Receive the following message in the console:
![error2 400](https://github.com/enBloc-org/kindly/assets/88290201/8fe54191-3bb8-4172-ae02-3b6c854b7e2e)

## Steps to Reproduce
1. Create a new item and add an image.
2. Go to your profile page or find your item in the appropriate category

**Comment by camelPhonso** [comment]
Thank you for creating this issue Yurii.

This is being discussed in #205 and it seems like it might be a supabase issue that we'll have to adapt to in development.

We'll keep the ticket here for the time being for reference but I expect it will be closed with the other issue.
