### ISSUE TITLE
Add our tests to CI pipeline 🧪 

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/kindly#273]
### Expected Behavior

With [Storybook](https://storybook.js.org/docs/get-started/install) now in our stack with component tests via the jest extension, plus the End-to-end testing via Cypress suites, we should run these in our CI pipeline. The simpler set up would be to run all tests for each PR merging into `dev`

### Current Behavior

Tests are only run if developers trigger them manually.

### Assignment

This issue is free for anyone to take

**Comment by mnixo** [comment]
!request

**Comment by mnixo** [comment]
Storybook facilitates the integration of different types of tests, some of them including:
- [Visual tests](https://storybook.js.org/docs/writing-tests/visual-testing).
    - Based on [Chromatic](https://www.chromatic.com/).
    - Focuses on visual regression testing, with the goal to catch unintended visual changes that could go unnoticed in other test types.
    - The Chromatic dashboard is feature-rich but could be cumbersome in a collaborative context.
    - Probably not as important as other types of tests.
    - Intended changes will still have to be reviewed manually.
- [Interaction tests](https://storybook.js.org/docs/writing-tests/interaction-testing).
    - Based on play functions. More play functions = more component documentation + more coverage.
    - Very functional.
    - Easy to follow in the Storybook UI.
    - The project already has a few play functions.
- [User flow tests](https://storybook.js.org/tutorials/ui-testing-handbook/react/en/user-flow-testing/).
    - Based on [Cypress](https://www.cypress.io/).
    - Nice DX with the Cypress UI.
    - Solid E2E option integrated in Storybook.
    - Don't need Supabase to run.
    - Would be nice to check how "E2E" they really are with a real use case.
    - Although there are already Cypress tests in the project, they might not be appropriate in this context.

It is important to note that these tests run in the context of Storybook, so there might be a few caveats.

For future reference, [this PR](https://github.com/mnixo/kindly/pull/10) has some exploratory work on how to integrate these in the project's CI.

**Comment by camelPhonso** [comment]
Closed this one as the PR associated has been merged.

But I'm curious on your take from looking at the user flow tests. To me it looks like having interaction tests for all our components and cypress e2e for the different user stories associated with each Milestone would be the better way to get decent coverage and the user flow stuff seems a bit redundant - specially if it actually ignores the context of the app 🤔

**Comment by mnixo** [comment]
>To me it looks like having interaction tests for all our components and cypress e2e for the different user stories associated with each Milestone would be the better way to get decent coverage and the user flow stuff seems a bit redundant - specially if it actually ignores the context of the app 🤔

There's definitely a considerable overlap between the two. Having a "real" E2E context (with Supabase) would definitely be better. In this case it seems that the user flow tests are just "as E2E as you can get" just within the Storybook context.
