### ISSUE TITLE
Allow users to browse before having to signup/login

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/kindly#276]
### Expected Behavior

Users should be able to browse through the homepage and the `/search` page before they have to login or signup.

The base of this issue is moving the signup / login requirement back to whenever a visitor tries to message about an item or upload an item of their own.

When they first visit Kindly, visitors should see the home page instead of the 'login' page

### Current Behavior

We are currently directed straight into the login / signup page

### Assignment

This issue is free for anyone to take

**Comment by mnixo** [comment]
!request
