### ISSUE TITLE
`bus error` on setup

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/kindly#283]
### Description of the Bug

We've found a few instances where new starters had trouble starting up their local environment. Attempting to run dev led to `bus errors` - this was traced back to the `package-lock.json` file.

Once package-lock was deleted and a new one created with `npm install` the environment started up fine again.

### What should happen instead

New contributors should just clone the repo, run `npm install` and be ready to code straight away.

### Steps to reproduce this bug

Unfortunately it's not an easily reproducible bug though it's been observed a couple of times with different collaborators.

### What could we do to solve this bug?

We need to figure out if this has happen more frequently and zone in on the actual cause before making a plan of action.

### Assignment

This issue is free for anyone to take

**Comment by mickeymarse** [comment]
As discussed in the Discord server, I tried cloning the repo again and running `npm i` **after deleting** `package-lock.json`.
However, that somehow caused an authentication error, which got solved after I've reinstalled the node modules with the original `package-lock.json`.

While it's true that the one mentioned by you is a common Node issue, I don't think what happened to me is.
My theory, and I'm just rambling here, is that something amongst the deprecated and unused modules and packages might be triggering this.
If so, the whole repo would benefit from a _cleanse_ first, before addressing this issue.

**Comment by camelPhonso** [comment]
> As discussed in the Discord server, I tried cloning the repo again and running `npm i` **after deleting** `package-lock.json`. However, that somehow caused an authentication error, which got solved after I've reinstalled the node modules with the original `package-lock.json`.
> 
> While it's true that the one mentioned by you is a common Node issue, I don't think what happened to me is. My theory, and I'm just rambling here, is that something amongst the deprecated and unused modules and packages might be triggering this. If so, the whole repo would benefit from a _cleanse_ first, before addressing this issue.

Thanks Mickey!

Following the chat on discord and your own test I think we might have zoned in on the wrong cause here - though this experiment with package-lock solved it we're not sure what exactly in the entire environment was causing the problem to begin with.

I've edited this issue to give a bit more detail and tagged it as a `spike` - in the coming weeks we should prompt new joiners to report back to here if they come across a similar problem so we can gather as much knowledge as possible on this before setting on a path to solve it.

**Comment by camelPhonso** [comment]
Closing this issue as in tests we've not been able to reproduce - this seems to be a wider setup problem and can be re-opened if a new instance is spotted
