### ISSUE TITLE
Add Cypress tests to CI 🌲 🌳

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/kindly#286]
### Expected Behavior

Similarly to what is happening with Storybook our E2E tests set up on cypress should be running for any PR's targeting `dev` as well as any targeting `main`.

### Current Behavior

E2E tests are only run manually and not a part of our CI pipeline

### Any other notes

This issue should take into account the changes being put into place through issue #263 since it sets default test users that can be used for these suites.

Currently tests will fail unless a test account is set for them prior to each run.

### Assignment

This issue is free for anyone to take

**Comment by mnixo** [comment]
!request
