### ISSUE TITLE
Update testing scripts and documentation guidance on E2E with Cypress

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/kindly#319]
### Expected Behavior

`TESTING.md` should let developers know how to run their E2E tests when needed.

### Current Behavior

we still have test scripts set up in `package.json` to run Playwright, which is no longer implemented and the documentation lets developers know how to run storybook and points to the official documentation, but has no details on cypress.

One of our dependencies `start-and-test` has been installed to allow for a single command to start the server and run e2e tests easily, this can be adapted to run our cypress suites instead of the original configuration for playwright

### Assignment

This issue is free for anyone to take

**Comment by mnixo** [comment]
!request
