### ISSUE TITLE
Item Sizes need updating (customer feedback)

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/kindly#340]
### Description of the Bug

This is not a breaking change but when a user selects a shoe in the `AddNewItemForm.tsx` they find a small selection of sizes which has been flagged doesn't include enough options.

![Image](https://github.com/user-attachments/assets/83d88c7c-9bc7-4cc6-8d0a-2bbbf986ba49)

### What should happen instead

We should target a wider selection - probably a good idea to match common sizes in large retail platforms![Image](https://github.com/user-attachments/assets/fc5536de-7589-4c71-b263-6bb37984f275)

### Steps to reproduce this bug

1. login
2. visit `/add-item`
3. select `clothes` or `shoes` for the item type
4. scroll through the options for sizes

### What could we do to solve this bug?

`AddNewItemForm.tsx` currently has an array of sizes to display. This can be adjusted (maybe we even find a more elegant way to do it)

### Assignment

This issue is free for anyone to take

**Comment by AnyaVeselova** [comment]
!request
Is it possible that they meant half sizes?

**Comment by camelPhonso** [comment]
> !request Is it possible that they meant half sizes?

the bot is having an off day - but you can have it :) thanks Anna!
