### ISSUE TITLE
Search Results Not Stored After Navigating Back from Item Page

### ISSUE THREAD

**Issue by OlenaReukova** [enBloc-org/kindly#343]
### Expected Behavior

The user should be returned to the filtered search results page, with all filters and search parameters.

### Current Behavior

When the user navigates back to the search results page after viewing an item, the search history is not stored, and the user is redirected to the main search page instead of the filtered results page.

The user applyed filter:
<img width="465" alt="filter kid clothing" src="https://github.com/user-attachments/assets/e0e35c91-c660-4914-9bdf-d914f2406bc4">

The user visits filtered item:
<img width="1437" alt="pick item" src="https://github.com/user-attachments/assets/fdc813ba-c8c7-4a75-9182-6ea5c5389b4b">

The user wants to return to the filtered search results page, but instead, the user is redirected to the main search page without any filters applied, forcing them to re-enter the search criteria.
<img width="1415" alt="redirection to search" src="https://github.com/user-attachments/assets/21a34b0f-1c8e-41db-9be0-5a67aa62d39e">

### Assignment

This issue is free for anyone to take

**Comment by AnyaVeselova** [comment]
!request
Thank you for such a clear explanation of the ticket, Olena! I want to give it a go. I have some experience of dealing with similar issue. My approach in one of my projects was to append search (filter) parameters to URL Query Params, however, this time I'd like to try to implement it with a state management library (like Redux or React Context).

**Comment by OlenaReukova** [comment]
@AnyaVeselova Thank you for your response! I’m glad to hear you’re eager to take on this ticket.

**Comment by camelPhonso** [comment]
Closing this issue pending a planning session to decide the direction of the feature - will re-open with directions on the desired behaviour after it's been planned with PO
