### ISSUE TITLE
Redesign homescreen

### ISSUE THREAD

**Issue by ShaughnAnderson94** [enBloc-org/kindly#358]
### Expected Behavior

![Image](https://github.com/user-attachments/assets/625f1030-5995-475e-9d3d-2b2822792f5e)

Home screen should look like this

### Current Behavior

looks like the version 1 home screen

### Any other notes

mobile version is still being designed

### Assignment

This issue is free for anyone to take

**Comment by AnyaVeselova** [comment]
! requested
