### ISSUE TITLE
Create Rollback branch 🌳 

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/kindly#360]
### Expected Behavior

Now that we have finished the development of all v1 features we should have a simple rollback strategy.

A snapshot branch should track the current state of V1 and the proper procedure to rollback to that state should be documented for the core team.

### Current Behavior

Our only stable version of the code lives on dev at the moment 😬 😰

### Assignment

This issue is free for anyone to take

**Comment by AnyaVeselova** [comment]
!request

Proposed Approach for Rollback Strategy Implementation:

1. use the git-snapshot command-line tool
2. Install git-snapshot: This tool will streamline creating and managing snapshots in Git.
3. I’ll take a snapshot of the current dev branch state.
4. The snapshot will be pushed to the remote repository to keep it accessible as a rollback point.
5. I’ll write clear instructions for the core team on how to use this snapshot for rollback, including steps for restoring the v1-snapshot if needed.

Let me know if you have any thoughts or additional requirements for this setup!
