### ISSUE TITLE
Rebase our migration history in the codebase 🔨

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/kindly#361]
### Expected Behavior

As we start working on V2 new developers should find their local database set up with a single migration file to declare their initial schema.

### Current Behavior

As a convention we are recording all changes to the database schema with new migration files within the codebase. The full history of changes to the database can be seen by reading through the files in the `migrations` folder.

This is done to make it easier for developers to practice version control and to provide a better development experience in the case that we need to debug any regression between different alterations to the schema.

However, with a new stable version ready for production we have a good opportunity to make this record leaner and track only newly relevant changes going forward.

### Assignment

This issue is free for anyone to take

**Comment by AnyaVeselova** [comment]
!request

**Comment by camelPhonso** [comment]
> !request

Hey @AnyaVeselova this issue is marked as core team as a result of a planning meeting we had, the bot should have stopped any automatic assignment, sorry for that.

**Comment by AnyaVeselova** [comment]
Oh, I'm very sorry @camelPhonso ! I've just read that the issue is free for anyone to take. I will pay attention to the "core team" label from now on.

**Comment by camelPhonso** [comment]
> Oh, I'm very sorry @camelPhonso ! I've just read that the issue is free for anyone to take. I will pay attention to the "core team" label from now on.

No worries Ana, the comment and the label are part of two different bits of automation we have on the project, which I can see get easily confusing. Thanks for jumping on a new issue though, this one just needs some specific action we've planned ahead for :)
