### ISSUE TITLE
Adjust CSS for Post An Item Page with Mobile-First Approach

### ISSUE THREAD

**Issue by OlenaReukova** [enBloc-org/kindly#380]
### Expected Behavior

Update the existing _Post An Item Page_ to align with a mobile-first approach, based on the provided designs for both desktop and mobile. The project utilises Tailwind CSS, and this ticket focuses on refining and adapting styles to prioritise mobile-first responsiveness for the home screen.

**Note:**
The header is excluded from this ticket and will be addressed separately.

**Mobile Design Screenshot for _Post An Item Page_** 

![Mobile Design Screenshot for _Post An Item Page_](https://github.com/user-attachments/assets/37e3ddd5-c750-48bb-af2b-53fdc4a65e66)

**Desktop Design Screenshot for _Post An Item Page_** 

![Desktop Design Screenshot for _Post An Item Page_](https://github.com/user-attachments/assets/2405a743-5a74-4263-b012-2ba05856a32d)

### Acceptance Criteria

- The _Post An Item Page_ matches the provided design specifications for both mobile and desktop views.
- Mobile-first styles are correctly applied, with graceful adjustments for larger screens using media queries.
- No major styling conflicts or layout issues are present across different devices and screen sizes.
![Image](https://github.com/user-attachments/assets/a6d05fb9-0b1e-46c6-bbf9-807f295dffb6)

### Current Behavior

The current _Post An Item Page_ may not fully reflect the new design specifications, particularly in terms of mobile-first responsiveness.

### Assignment

This issue is free for anyone to take

**Comment by Edga380** [comment]
!request
