### ISSUE TITLE
Fix viewport height to account for nav and footer 🍌

### ISSUE THREAD

**Issue by eliazzo** [enBloc-org/kindly#73]
The message form should remain visible when scrolling, this means adjusting the viewport height to account for the navbar and bottom bar

**Comment by nichgalzin** [comment]
Hey @YuraPetrovskyi ,
   I've been working on this and am almost finished. So I would not spend more time on this. Thanks!

**Comment by YuraPetrovskyi** [comment]
Thank you Nick for letting me know. I also worked on this a little bit. But
anyway, it was useful for me to understand what it was all about)

пт, 17 трав. 2024 р. о 11:42 Nich Galzin ***@***.***> пише:
